name: "\U0001F41E Bug report"
description: Report a bug in Warewulf (command not working as expected, etc.)
labels: [bug]
body:
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: |
        Explain, in a clear and concise way, the command you ran and the result you were trying to achieve.
        Example: "I ran `wwctl node list` to list all nodes, and ..."
      placeholder: |
        ```console
        $ wwctl <command1>
        $ wwctl <command2>
        ...
        ```
    validations:
      required: true
  - type: textarea
    id: error
    attributes:
      label: Error message
      description: |
        If Warewulf reported an error, provide the error message. If it did not
        report an error but the output appears incorrect, provide the incorrect
        output. If there was no error message and no output but the result is
        incorrect, describe how it does not match what you expect.

        Also include any pertinent logs from warewulfd, typically available
        with `journalctl -u warewulfd.service`.
      placeholder: |
        ```console
        $ wwctl <command1>
        $ wwctl <command2>
        $ journalctl -u warewulfd.service --since
        ```
  - type: textarea
    id: information
    attributes:
      label: Information on your system
      description: Please include the output of `wwctl version` and the contents of `/etc/os-release`
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        If you have any relevant configuration detail (`nodes.conf` or `warewulf.conf`, etc.) you can add that here as well.
  - type: checkboxes
    id: checks
    attributes:
      label: General information
      options:
        - label: I have run `wwctl version` and reported the contents of `/etc/os-release`
          required: true
        - label: I have searched the issues of this repo and believe this is not a duplicate
          required: true
        - label: I have captured and reported relevant error messages and logs
          required: true
  - type: markdown
    attributes:
      value: |
        We encourage you to try, as much as possible, to reduce your problem to
        the minimal example that still reproduces the issue. That would help us
        a lot in fixing it quickly and effectively!

        If you want to ask a question about Warewulf (how to use it, what it
        can currently do, etc.), try the `#warewulf` channel on [our
        Slack](https://warewulf.org/help) first. We have a welcoming community
        and chances are you'll get your reply faster and without opening an
        issue.

        Other than that, thanks for taking the time to contribute to Warewulf!
